# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import configuracoesGrpc_pb2 as configuracoesGrpc__pb2


class GerenciadorDeNotasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Mensagem = channel.unary_unary(
                '/GerenciadorDeNotas/Mensagem',
                request_serializer=configuracoesGrpc__pb2.Requisicao.SerializeToString,
                response_deserializer=configuracoesGrpc__pb2.Resposta.FromString,
                )


class GerenciadorDeNotasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Mensagem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GerenciadorDeNotasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Mensagem': grpc.unary_unary_rpc_method_handler(
                    servicer.Mensagem,
                    request_deserializer=configuracoesGrpc__pb2.Requisicao.FromString,
                    response_serializer=configuracoesGrpc__pb2.Resposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GerenciadorDeNotas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GerenciadorDeNotas(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Mensagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GerenciadorDeNotas/Mensagem',
            configuracoesGrpc__pb2.Requisicao.SerializeToString,
            configuracoesGrpc__pb2.Resposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
